// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzdbjethgcdpnraljguk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6ZGJqZXRoZ2NkcG5yYWxqZ3VrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MzYyMTQsImV4cCI6MjA3MTAxMjIxNH0.JxEWLSkYS1hAIE3Fh7ziC1NlxuhRuJjV2Igz1P5mOc0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});